---
title: 'Lab 06: Income Prediction'
author: "Benjamin Preston 9029520"
date: "2024-04-29"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(rpart)
library(tidyverse)
setwd("/Users/bpreston/Library/CloudStorage/GoogleDrive-bhp1972@gmail.com/My Drive/_bhp1972/Study/Auckland/STAT765/Sandbox765/Lab6")

```

## Task 1

```{r data, message = FALSE}

set.seed(520)

# Load the adult data set
# 
adult.df <- read_table('adult.data', col_names=F)

# Clean and wrangle data
# New names for columns in df
# 
new_names <- c('age', 'workclass', 'fnlwgt', 'education',
              'education_num', 'marital_status', 'occupation',
              'relationship', 'race', 'sex', 'capital_gain',
              'capital_loss', 'hours_per_week', 'native_country',
              'response')

# String cleaning functions and coerce to double / factor
# 
strCleanDbl <- function(x) as.double(str_replace(x, ",$", ""))
strCleanFact <- function(x) as.factor(str_replace(x, ",$", ""))


adult.df <- adult.df |> 
  rename_with(~ new_names, everything()) |> 
  mutate(across(starts_with("capital"), strCleanDbl),
         response = ifelse(response == '>50K', 1, 0),
         across(where(is.character), strCleanFact)
         )

# Split into separate training and testing data sets
#
train_index <- sample(nrow(adult.df), 0.8 * nrow(adult.df)) # 80% for training
test_index <- setdiff(1:nrow(adult.df), train_index) # 20% for testing

train.df <- adult.df[train_index,]
test.df <- adult.df[test_index,]

dim(train.df); dim(test.df)

summary(train.df)

```

1e.  Key predictors will include gender, age, education, occupation, and hours per week.  

## Task 2 Build a Decision Tree

```{r decision}

# 2a. Build a decision tree using the rpart function
# 

tree <- rpart(response ~ ., data=train.df, method='class', parms = list(split = "surrogate"))

# I have included a "surrogate" parameter here to specify that surrogate splits should be used
# When a primary split is missing, surrogate splits are used to determine the best split
# This happens in the (randomly sampled) test data where there is only one instance of 
# a particular value of a variable (native country = "Holand-Netherlands"))  

summary(tree)

plot(tree, margin = 0.1); text(tree, cex=0.5)

# Variable importance
# 
(tree$variable.importance)

printcp(tree)
plotcp(tree)

pred_train <- predict(tree, newdata=train.df[,-15], type='class')
table(actual = train.df$response, predicted = pred_train)
sum(train.df$response == pred_train) / nrow(train.df)

pred_test <- predict(tree, newdata=test.df[,-15], type='class')
table(actual = test.df$response, predicted = pred_test)
sum(test.df$response == pred_test) / nrow(test.df)



```
